# Generated by Django 4.2 on 2023-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('profile_pic', models.FileField(max_length=255, upload_to='media/Images')),
            ],
        ),
    ]
